version: '3.7'
services:

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    image: poc-api:latest
    restart: on-failure
    environment:
        DATABASE_URL: mysql://poc:poc@mysql:3306/poc
        PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    depends_on:
      - mysql
      - redis

  cron:
    image: poc-api:latest
    restart: on-failure
    environment:
      CONTAINER_ROLE: cron
      DATABASE_URL: mysql://poc:poc@mysql:3306/poc
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    depends_on:
      - api

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: poc
      MYSQL_DATABASE: poc
      MYSQL_USER: poc
      MYSQL_PASSWORD: poc
    ports:
      - '${EFTPOS_MYSQL_PORT:-3306}:3306'

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '${EFTPOS_NGINX_PORT:-80}:80'
    depends_on:
      - api

  redis:
    image: redis:alpine

  worker:
    image: poc-api:latest
    command: "php bin/console messenger:consume -vv"
    restart: on-failure
    environment:
        DATABASE_URL: mysql://poc:poc@mysql:3306/poc
        PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    depends_on:
      - api
